const loader=document.querySelector('.loader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),650));
const nav=document.querySelector('.nav');document.querySelector('.menu')?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const reveals=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});reveals.forEach(e=>observer.observe(e));
const visual=document.querySelector('[data-tilt]');visual?.addEventListener('pointermove',e=>{if(innerWidth<800)return;const r=visual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;visual.style.transform=`rotateY(${x*3}deg) rotateX(${-y*3}deg)`});visual?.addEventListener('pointerleave',()=>visual.style.transform='');
const features=[{k:'01 / SILENCE',t:'Hear<br>the <em>difference.</em>',p:'Our fan architecture moves air with a soft, steady rhythm. At night, it drops to just 19 dB — quieter than a whisper.'},{k:'02 / PURITY',t:'Breathe<br><em>cleaner.</em>',p:'A multi-stage filter captures fine particles and everyday pollutants, helping the air in your room feel noticeably fresher.'},{k:'03 / INTELLIGENCE',t:'Comfort<br>that <em>thinks.</em>',p:'Sensors learn the room around you and continuously tune airflow and temperature, so your setting stays effortless.'}];
const fk=document.querySelector('#featureKicker'),ft=document.querySelector('#featureTitle'),fp=document.querySelector('#featureText');document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{const f=features[+b.dataset.feature];if(!fk||!ft||!fp)return;fk.textContent=f.k;ft.innerHTML=f.t;fp.textContent=f.p;document.querySelectorAll('[data-feature]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
const form=document.querySelector('#contactForm'),note=document.querySelector('#formNote');form?.addEventListener('submit',e=>{e.preventDefault();if(note)note.textContent='Thanks — your consultation request is ready. We’ll be in touch shortly.';if(note)note.style.color='#1d7f3a';const btn=form.querySelector('button');if(btn){btn.innerHTML='Request received ✓';btn.disabled=true}});
const stage=document.querySelector('.feature-stage'),pin=document.querySelector('.feature-pin');window.addEventListener('scroll',()=>{if(!stage||!pin)return;const r=stage.getBoundingClientRect(),max=stage.offsetHeight-innerHeight,p=Math.min(1,Math.max(0,-r.top/max));const index=Math.min(2,Math.floor(p*3));const active=document.querySelector(`[data-feature="${index}"]`);if(active&&!active.classList.contains('active'))active.click();const img=pin.querySelector('.feature-image');if(img)img.style.background=`radial-gradient(circle at ${55+p*30}% ${42+p*10}%, #314a5a 0, #11181c 25%, #080808 58%)`});
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduce){document.querySelectorAll('.button,.nav-button').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.06}px,${(e.clientY-r.top-r.height/2)*.06}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const cursor=document.createElement('div');cursor.className='cursor-glow';document.body.appendChild(cursor);window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'})}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}}));
