const loader=document.querySelector('.loader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),650));
const nav=document.querySelector('.nav');document.querySelector('.menu')?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const reveals=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});reveals.forEach(e=>observer.observe(e));
const visual=document.querySelector('[data-tilt]');visual?.addEventListener('pointermove',e=>{if(innerWidth<800)return;const r=visual.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;visual.style.transform=`rotateY(${x*3}deg) rotateX(${-y*3}deg)`});visual?.addEventListener('pointerleave',()=>visual.style.transform='');
const features=[{k:'01 / SILENCE',t:'Hear<br>the <em>difference.</em>',p:'Our fan architecture moves air with a soft, steady rhythm. At night, it drops to just 19 dB — quieter than a whisper.'},{k:'02 / PURITY',t:'Breathe<br><em>cleaner.</em>',p:'A multi-stage filter captures fine particles and everyday pollutants, helping the air in your room feel noticeably fresher.'},{k:'03 / INTELLIGENCE',t:'Comfort<br>that <em>thinks.</em>',p:'Sensors learn the room around you and continuously tune airflow and temperature, so your setting stays effortless.'}];
const fk=document.querySelector('#featureKicker'),ft=document.querySelector('#featureTitle'),fp=document.querySelector('#featureText');document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{const f=features[+b.dataset.feature];if(!fk||!ft||!fp)return;fk.textContent=f.k;ft.innerHTML=f.t;fp.textContent=f.p;document.querySelectorAll('[data-feature]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));
const form=document.querySelector('#contactForm'),note=document.querySelector('#formNote');form?.addEventListener('submit',e=>{e.preventDefault();if(note)note.textContent='Thanks — your consultation request is ready. We’ll be in touch shortly.';if(note)note.style.color='#1d7f3a';const btn=form.querySelector('button');if(btn){btn.innerHTML='Request received ✓';btn.disabled=true}});
const stage=document.querySelector('.feature-stage'),pin=document.querySelector('.feature-pin');window.addEventListener('scroll',()=>{if(!stage||!pin)return;const r=stage.getBoundingClientRect(),max=stage.offsetHeight-innerHeight,p=Math.min(1,Math.max(0,-r.top/max));const index=Math.min(2,Math.floor(p*3));const active=document.querySelector(`[data-feature="${index}"]`);if(active&&!active.classList.contains('active'))active.click();const img=pin.querySelector('.feature-image');if(img)img.style.background=`radial-gradient(circle at ${55+p*30}% ${42+p*10}%, #314a5a 0, #11181c 25%, #080808 58%)`});
const assembly=document.querySelector('.assembly-bg');const parts=[...document.querySelectorAll('.assembly-bg .ac-part')];const labels=[...document.querySelectorAll('.assembly-bg .assembly-label')];const motionReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function renderAssembly(){if(!assembly)return;const h=Math.max(document.documentElement.scrollHeight-innerHeight,1),p=Math.min(1,Math.max(0,scrollY/h));const explode=Math.sin(p*Math.PI);const mobile=innerWidth<681,s=mobile?.68:1;const configs=[{x:0,y:-35,z:90,r:-2,sc:1.05,o:1},{x:-22,y:-170,z:30,r:-4,sc:1.08,o:1},{x:18,y:135,z:70,r:10,sc:1.06,o:1},{x:-150,y:105,z:100,r:-8,sc:1.08,o:.95},{x:145,y:-105,z:110,r:7,sc:1.08,o:.95},{x:0,y:0,z:0,r:0,sc:1,o:1}];parts.forEach((el,n)=>{const c=configs[n]||configs[5],x=c.x*explode*s,y=c.y*explode*s,z=c.z*explode*s;el.style.transform=`translate3d(calc(-50% + ${x}px),calc(-50% + ${y}px),${z}px) rotate(${c.r*explode}deg) scale(${1+(c.sc-1)*explode})`;el.style.opacity=n===0?(explode>.08?c.o:0):c.o});assembly.classList.toggle('is-exploded',explode>.12);labels.forEach(l=>l.style.opacity=explode>.18?String(Math.min(1,(explode-.18)*2.5)):'');const halo=assembly.querySelector('.assembly-halo');if(halo)halo.style.transform=`scale(${1+explode*.28})`;assembly.style.opacity=explode>.06?String(.08+.22*Math.min(1,explode*1.8)):'0'}
if(assembly&&!motionReduced){renderAssembly();let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{renderAssembly();ticking=false});ticking=true}},{passive:true});addEventListener('resize',renderAssembly)}
if(!motionReduced){document.querySelectorAll('.button,.nav-button').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.06}px,${(e.clientY-r.top-r.height/2)*.06}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const cursor=document.createElement('div');cursor.className='cursor-glow';document.body.appendChild(cursor);addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'})}
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:motionReduced?'auto':'smooth',block:'start'})}}));

// SMART SOLUTION identity and editorial copy
document.title='Smart Solution — Cooling, reimagined.';
const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.nodeValue.includes('AERIS'))n.nodeValue=n.nodeValue.replaceAll('AERIS','SMART SOLUTION')});
document.querySelectorAll('.brand').forEach(el=>{el.setAttribute('aria-label','Smart Solution home');el.innerHTML='<span class="brand-dot"></span><span class="smart-brand">SMART <b>SOLUTION</b></span>'});
const heroTitle=document.querySelector('.hero h1'),heroSub=document.querySelector('.hero-sub'),heroEyebrow=document.querySelector('.hero .eyebrow');if(heroEyebrow)heroEyebrow.textContent='SMART SOLUTION / SIGNATURE SERIES';if(heroTitle)heroTitle.innerHTML='Cooling,<br><em>reimagined.</em>';if(heroSub)heroSub.textContent='Intelligent climate control for the way you live. Quiet comfort, cleaner air and effortless control — engineered around you.';
const statementTitle=document.querySelector('.statement h2');if(statementTitle)statementTitle.innerHTML='Comfort that<br><em>disappears.</em>';const statementP=document.querySelector('.statement-inner>p:last-child');if(statementP)statementP.textContent='We removed the noise, clutter and guesswork from cooling. What remains is a calm, intelligent experience that simply belongs in your home.';
const collection=document.querySelector('.models h2');if(collection)collection.innerHTML='Find your <em>perfect climate.</em>';const numberTitle=document.querySelector('.number-intro h2');if(numberTitle)numberTitle.innerHTML='Engineered quietly.<br><em>Built brilliantly.</em>';const expTitle=document.querySelector('.experience-head h2');if(expTitle)expTitle.innerHTML='From first touch<br>to <em>perfect air.</em>';const quote=document.querySelector('.quote blockquote');if(quote)quote.innerHTML='It does not feel like an appliance. It feels like the room simply became <em>better.</em>';const contactTitle=document.querySelector('.contact h2');if(contactTitle)contactTitle.innerHTML='Make room for<br><em>better air.</em>';

// Remove the experimental assembly layer entirely. The background is now intentionally calm and product-led.
document.querySelector('.assembly-bg')?.remove();
const atmosphere=document.createElement('style');atmosphere.textContent=`body{background:#f5f5f7;overflow-x:hidden}.smart-brand{letter-spacing:-.035em}.smart-brand b{font-weight:800}.hero{background:radial-gradient(circle at 72% 44%,rgba(214,232,242,.8) 0,rgba(245,245,247,0) 36%),linear-gradient(180deg,#fff 0%,#f7f8f9 100%)}.hero:after{content:'';position:absolute;inset:auto 0 0;height:30%;pointer-events:none;background:linear-gradient(transparent,rgba(245,245,247,.8));z-index:1}.hero-visual{z-index:2}.hero-copy{z-index:4}.hero-visual:before{content:'';position:absolute;width:72%;aspect-ratio:1;border-radius:50%;background:radial-gradient(circle,rgba(196,222,236,.55),transparent 68%);filter:blur(22px);animation:ambientFloat 8s ease-in-out infinite}.hero-visual:after{content:'';position:absolute;width:62%;height:1px;bottom:17%;background:linear-gradient(90deg,transparent,rgba(110,110,115,.16),transparent)}@keyframes ambientFloat{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-12px) scale(1.03)}}.statement{background:linear-gradient(180deg,#f5f5f7,#fff)}.models{background:#fff}.numbers{background:#f5f5f7}.experience{background:#fff}.contact{background:#f5f5f7}@media(max-width:680px){.smart-brand{font-size:11px}.hero-visual:before{width:100%}}`;document.head.appendChild(atmosphere);
